/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

var listController = {
    // This object acts as a controller for the list UI.
    // It implements the dataSource methods for the list.
    
    numberOfRows: function() {
        // The List calls this dataSource method to find out how many rows should be in the list.
        return torrentSrc.items().length;
    },
    
    prepareRow: function(rowElement, rowIndex, templateElements) {
        // The List calls this dataSource method for every row.  templateElements contains references to all elements inside the template that have an id. We use it to fill in the text of the rowTitle element.
        if (templateElements.rowTitle) {
            templateElements.rowTitle.innerText = resorts[rowIndex].name;
        }

        // We also assign an onclick handler that will cause the browser to go to the detail page.
        var self = this;
        var handler = function() {
            var resort = resorts[rowIndex];
            detailController.setResort(resort);
            var browser = document.getElementById('browser').object;
            // The Browser's goForward method is used to make the browser push down to a new level.  Going back to previous levels is handled automatically.
            browser.goForward(document.getElementById('detailLevel'), resort.name);
        };
        rowElement.onclick = handler;
    }
};

var detailController = {
    // This object acts as a controller for the detail UI.
    
    setTorrent: function(torrent) {
        this._torrent = torrent;
        
        
    }
    
};

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    torrents.loadData();
}

// Sample data.  Some applications may have static data like this, but most will want to use information fetched remotely via XMLHttpRequest.
var torrents = {
    _items: [],
    loadData: function() {
        // Values you provide
        var feedURL = "http://192.168.0.15:1337/gui/"; // The feed to fetch

        // XMLHttpRequest setup code
        var xmlRequest = new XMLHttpRequest();
        xmlRequest.onload = this.loadDataFinished;
        xmlRequest.open("GET", feedURL);
        xmlRequest.setRequestHeader("Cache-Control", "no-cache");
        xmlRequest.send(null);
    },
    
    loadDataFinished: function(xmlRequest) {
        if (xmlRequest.status == 200) {
            // Parse and interpret results
            // XML results found in xmlRequest.responseXML
            // Text results found in xmlRequest.responseText
            this._items = eval('('+xmlRequest.responseText + ')');
        }
        else {
            alert("Error fetching data: HTTP status " + xmlRequest.status);
        }
    }
};
