/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "back_button": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 50, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back" },
    "browser": { "creationFunction": "CreateBrowser" },
    "detailFileName": { "creationFunction": "CreateText", "text": "File 1" },
    "detailFilePercent": { "creationFunction": "CreateText", "text": "25%" },
    "detailInfo": { "creationFunction": "CreateText", "text": "D: 23 KB/s   U: 23 KB/s" },
    "detailName": { "creationFunction": "CreateText", "text": "Gentoo-2008.0-i386.iso" },
    "detailPercent": { "creationFunction": "CreateText", "text": "25%" },
    "detailProgressBar": { "creationFunction": "CreateHorizontalLevelIndicator", "criticalValue": 101, "imageCritical": "Images/on.png", "imageHeight": 15, "imageOff": "Images/off.png", "imageOn": "Images/on.png", "imageWarning": "Images/on.png", "imageWidth": 3, "maxValue": 100, "onValue": 1, "value": 25, "warningValue": 101 },
    "downLbl": { "creationFunction": "CreateText", "text": "D:" },
    "downSpd": { "creationFunction": "CreateText", "text": "23 KB/s" },
    "header": { "creationFunction": "CreateHeader", "rootTitle": "iTorrent" },
    "name": { "creationFunction": "CreateText", "text": "Gentoo_2008.0_i386.iso" },
    "percent": { "creationFunction": "CreateText", "text": "25.0%" },
    "progressBar": { "creationFunction": "CreateHorizontalLevelIndicator", "criticalValue": 15, "imageCritical": "Images/on.png", "imageHeight": 15, "imageOff": "Images/off.png", "imageOn": "Images/on.png", "imageWarning": "Images/on.png", "imageWidth": 3, "maxValue": 100, "onValue": 1, "warningValue": 10 },
    "stackLayout": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "startButton": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 90, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Start" },
    "stopButton": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 90, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Stop" },
    "text": { "creationFunction": "CreateText", "text": "Files" },
    "torrentFileList": { "creationFunction": "CreateList", "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "detailListController", "labelElementId": "detailFileName", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 3, "useDataSource": true },
    "torrentList": { "creationFunction": "CreateList", "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "listController", "labelElementId": "name", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 3, "useDataSource": true },
    "upLbl": { "creationFunction": "CreateText", "text": "U:" },
    "upSpd": { "creationFunction": "CreateText", "text": "23 KB/s" }
};
